/** CSS line-clamp / ellipsis ile kesilen metin alanları — global tooltip hedefleri. */
export const CLAMPED_TEXT_TOOLTIP_SELECTORS = [
  ".featured-institutions-list-card-title",
  ".featured-institution-name",
  ".featured-institution-subcategory",
  ".category-results-card-title",
  ".category-results-card-description",
  ".category-results-card-location span",
  ".category-results-card-subcategory-badge",
  ".category-filter-checkbox-label",
  ".blog-card-title-new",
  ".blog-card-excerpt",
  ".search-result-name",
  ".search-result-description",
  ".service-card-title",
  ".service-card-categories",
  ".purple-featured-card-title",
  ".announcement-featured-title",
  ".announcement-featured-desc",
  ".announcement-small-title",
  ".announcement-small-desc",
  ".home-main-category-card-title",
  ".favorite-card-title",
  ".favorite-card-description",
  ".featured-post-excerpt",
  ".blog-list-item-excerpt",
  ".panel-overview-announcements-item-desc",
  ".panel-announcements-desc-clamp",
  ".panel-institutions-feature-select-label",
  ".panel-institutions-feature-select-option",
  ".okullar-table-cell-truncate",
  ".okullar-category-badge",
  ".okullar-category-dropdown-label",
  ".header-hamburger-welcome-name",
  ".institution-announcement-desc",
  ".nasil-calisir-feature-card-description",
  ".signup-date-picker-trigger-text",
  "[data-tooltip-text]",
].join(", ");

export const CLAMPED_TEXT_TOOLTIP_IGNORE_SELECTORS =
  ".clamped-text-tooltip-wrap, .clamped-text-tooltip, .leaflet-tooltip, .leaflet-popup";
