"use client";

import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import {
  INSTRUCTOR_PROFILE_ROW_SELECT,
  INSTRUCTORS_TABLE,
  type InstructorProfileRow,
} from "@/lib/instructorProfileClient";

/** Tüm eğitmen görselleri (profil, galeri, duyuru) — kurum paneli institution-media ile aynı model */
export const INSTRUCTOR_MEDIA_BUCKET = "instructor-media";
export const INSTRUCTOR_CV_FILES_BUCKET = "instructor-cv-files";
export const INSTRUCTOR_DIPLOMA_FILES_BUCKET = "instructor-diploma-files";
export const INSTRUCTOR_MEDIA_TABLE = "instructor_media" as const;

export const INSTRUCTOR_MEDIA_IMAGE_ERROR = "Lütfen geçerli bir görsel dosyası seçin.";
export const INSTRUCTOR_MEDIA_CV_ERROR =
  "Lütfen PDF, DOC veya DOCX formatında bir CV yükleyin.";
export const INSTRUCTOR_MEDIA_DIPLOMA_ERROR =
  "Lütfen PDF, JPG, JPEG veya PNG formatında bir diploma / belge yükleyin.";
export const INSTRUCTOR_MEDIA_DIPLOMA_SIZE_ERROR =
  "Diploma / belge en fazla 10MB olabilir.";
export const INSTRUCTOR_MEDIA_UPLOAD_ERROR = "Dosya yüklenirken bir hata oluştu.";
export const INSTRUCTOR_MEDIA_DELETE_ERROR = "Dosya silinirken bir hata oluştu.";
export const INSTRUCTOR_MEDIA_PROFILE_SUCCESS = "Profil fotoğrafı başarıyla güncellendi.";
export const INSTRUCTOR_MEDIA_CV_SUCCESS = "CV başarıyla güncellendi.";
export const INSTRUCTOR_MEDIA_GALLERY_DELETE_SUCCESS = "Görsel başarıyla silindi.";
export const INSTRUCTOR_MEDIA_CV_NOT_FOUND_ERROR =
  "CV dosyası bulunamadı. Lütfen CV'yi yeniden yükleyin.";

const ALLOWED_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const ALLOWED_CV_TYPES = new Set([
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
]);
const ALLOWED_DIPLOMA_TYPES = new Set([
  "application/pdf",
  "image/jpeg",
  "image/jpg",
  "image/png",
]);

const PROFILE_PHOTO_MAX_BYTES = 10 * 1024 * 1024;
const GALLERY_IMAGE_MAX_BYTES = 10 * 1024 * 1024;
const ANNOUNCEMENT_IMAGE_MAX_BYTES = 10 * 1024 * 1024;
const CV_MAX_BYTES = 15 * 1024 * 1024;
export const INSTRUCTOR_DIPLOMA_MAX_BYTES = 10 * 1024 * 1024;

export type InstructorGalleryMediaRow = {
  id: number;
  instructor_id: number;
  owner_auth_id: string;
  file_url: string;
  file_path: string;
  file_name: string | null;
  file_type: string | null;
  media_type: string;
  created_at: string | null;
};

export const INSTRUCTOR_MEDIA_TABLE_MISSING_SQL = `-- public.instructor_media tablosu (galeri) gerekli
CREATE TABLE IF NOT EXISTS public.instructor_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id bigint NOT NULL REFERENCES public.instructors(id) ON DELETE CASCADE,
  owner_auth_id uuid NOT NULL,
  file_url text NOT NULL,
  file_path text NOT NULL,
  file_name text,
  file_type text,
  media_type text NOT NULL DEFAULT 'gallery',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS instructor_media_instructor_id_idx
  ON public.instructor_media (instructor_id);

CREATE INDEX IF NOT EXISTS instructor_media_owner_auth_id_idx
  ON public.instructor_media (owner_auth_id);

ALTER TABLE public.instructor_media ENABLE ROW LEVEL SECURITY;`;

type InstructorMediaFolder = "profile" | "gallery" | "announcements";

function safeStorageFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/_+/g, "_").slice(0, 120);
}

function buildTimestampedStorageFileName(originalName: string, fallbackExt: string): string {
  const timestamp = Date.now();
  const cleanName = safeStorageFileName(originalName) || `${timestamp}.${fallbackExt}`;
  return `${timestamp}-${cleanName}`;
}

function buildInstructorMediaPath(
  instructorId: number,
  folder: InstructorMediaFolder,
  fileName: string,
): string {
  return `instructors/${instructorId}/${folder}/${fileName}`;
}

function buildInstructorCvPath(instructorId: number, fileName: string): string {
  return `instructors/${instructorId}/cv/${fileName}`;
}

function buildInstructorDiplomaPath(instructorId: number, fileName: string): string {
  return `instructors/${instructorId}/diploma/${fileName}`;
}

function getInstructorMediaPublicUrl(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  path: string,
): string {
  return supabase.storage.from(INSTRUCTOR_MEDIA_BUCKET).getPublicUrl(path).data.publicUrl ?? "";
}

export function isValidInstructorImageFile(file: File): boolean {
  return ALLOWED_IMAGE_TYPES.has(file.type);
}

export function isValidInstructorCvFile(file: File): boolean {
  if (ALLOWED_CV_TYPES.has(file.type)) return true;
  const lower = file.name.toLowerCase();
  return lower.endsWith(".pdf") || lower.endsWith(".doc") || lower.endsWith(".docx");
}

export function isValidInstructorDiplomaFile(file: File): boolean {
  if (ALLOWED_DIPLOMA_TYPES.has(file.type)) return true;
  const lower = file.name.toLowerCase();
  return (
    lower.endsWith(".pdf") ||
    lower.endsWith(".jpg") ||
    lower.endsWith(".jpeg") ||
    lower.endsWith(".png")
  );
}

export function isInstructorMediaTableMissingError(error: {
  code?: string;
  message?: string;
} | null): boolean {
  if (!error) return false;
  const code = String(error.code ?? "");
  const msg = String(error.message ?? "").toLowerCase();
  return (
    code === "42P01" ||
    code === "PGRST205" ||
    (msg.includes("instructor_media") &&
      (msg.includes("does not exist") || msg.includes("could not find")))
  );
}

export function extractStoragePathFromPublicUrl(
  publicUrlOrPath: string,
  bucket: string,
): string | null {
  const raw = String(publicUrlOrPath ?? "").trim();
  if (!raw) return null;
  if (!raw.includes("://")) {
    return raw.replace(/^\/+/, "");
  }
  try {
    const url = new URL(raw);
    const marker = `/storage/v1/object/public/${bucket}/`;
    const idx = url.pathname.indexOf(marker);
    if (idx >= 0) {
      return decodeURIComponent(url.pathname.slice(idx + marker.length));
    }
  } catch {
    return null;
  }
  return null;
}

/** Public görsel URL veya storage yolu → instructor-media içindeki path */
function resolveInstructorMediaStoragePath(publicUrlOrPath: string): string | null {
  const raw = String(publicUrlOrPath ?? "").trim();
  if (!raw) return null;

  const fromUrl = extractStoragePathFromPublicUrl(raw, INSTRUCTOR_MEDIA_BUCKET);
  if (fromUrl) return fromUrl;

  if (!raw.includes("://")) {
    return raw.replace(/^\/+/, "");
  }
  return null;
}

async function removeStorageFileQuietly(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  bucket: string,
  path: string | null | undefined,
): Promise<void> {
  const p = String(path ?? "").trim();
  if (!p) return;
  const { error } = await supabase.storage.from(bucket).remove([p]);
  if (error) {
    console.warn(`[instructor-media] storage remove (${bucket}):`, error);
  }
}

async function removeInstructorPublicImageQuietly(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  publicUrlOrPath: string | null | undefined,
): Promise<void> {
  const path = resolveInstructorMediaStoragePath(String(publicUrlOrPath ?? ""));
  if (!path) return;
  await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, path);
}

async function removeGalleryStorageForItem(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  item: InstructorGalleryMediaRow,
): Promise<void> {
  const filePath = String(item.file_path ?? "").trim();
  if (filePath) {
    await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, filePath);
    return;
  }

  const pathFromUrl = resolveInstructorMediaStoragePath(String(item.file_url ?? ""));
  if (pathFromUrl) {
    await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, pathFromUrl);
  }
}

async function uploadInstructorPublicImage(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  instructorId: number,
  folder: InstructorMediaFolder,
  file: File,
  maxBytes: number,
): Promise<{ path: string; publicUrl: string } | { error: string }> {
  if (!isValidInstructorImageFile(file)) {
    return { error: INSTRUCTOR_MEDIA_IMAGE_ERROR };
  }
  if (file.size > maxBytes) {
    return { error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const storageFileName = buildTimestampedStorageFileName(file.name, "jpg");
  const path = buildInstructorMediaPath(instructorId, folder, storageFileName);

  const { error: uploadError } = await supabase.storage
    .from(INSTRUCTOR_MEDIA_BUCKET)
    .upload(path, file, { upsert: false, contentType: file.type });

  if (uploadError) {
    console.error(`[instructor-media] ${folder} upload:`, uploadError);
    return { error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  return { path, publicUrl: getInstructorMediaPublicUrl(supabase, path) };
}

async function updateInstructorMediaColumn(
  supabase: ReturnType<typeof createSupabaseBrowserClient>,
  authUid: string,
  instructorId: number,
  patch: { profile_picture?: string | null; cv_url?: string | null; diploma_document_path?: string | null },
): Promise<{ row: InstructorProfileRow | null; error: string | null }> {
  const { data, error } = await supabase
    .from(INSTRUCTORS_TABLE)
    .update(patch)
    .eq("id", instructorId)
    .eq("owner_auth_id", authUid)
    .select(INSTRUCTOR_PROFILE_ROW_SELECT)
    .maybeSingle();

  if (error) {
    console.error("[instructors] media column update:", error);
    return { row: null, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }
  if (!data) {
    return { row: null, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }
  return { row: data as InstructorProfileRow, error: null };
}

/** instructors.cv_url — storage yolu veya tam Supabase URL */
export function resolveInstructorCvStoragePath(cvUrlOrPath: string): string | null {
  const raw = String(cvUrlOrPath ?? "").trim();
  if (!raw) return null;

  const fromPublic = extractStoragePathFromPublicUrl(raw, INSTRUCTOR_CV_FILES_BUCKET);
  if (fromPublic) return fromPublic;

  if (!raw.includes("://")) {
    return raw.replace(/^\/+/, "");
  }

  try {
    const url = new URL(raw);
    const bucket = INSTRUCTOR_CV_FILES_BUCKET;
    const markers = [
      `/storage/v1/object/sign/${bucket}/`,
      `/storage/v1/object/authenticated/${bucket}/`,
      `/storage/v1/object/public/${bucket}/`,
    ];
    for (const marker of markers) {
      const idx = url.pathname.indexOf(marker);
      if (idx >= 0) {
        return decodeURIComponent(url.pathname.slice(idx + marker.length));
      }
    }
  } catch {
    return null;
  }
  return null;
}

export async function uploadInstructorProfilePhotoClient(
  authUid: string,
  instructorId: number,
  file: File,
  currentProfilePicture: string | null | undefined,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ row: InstructorProfileRow | null; error: string | null }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  const uploaded = await uploadInstructorPublicImage(
    supabase,
    instructorId,
    "profile",
    file,
    PROFILE_PHOTO_MAX_BYTES,
  );
  if ("error" in uploaded) {
    return { row: null, error: uploaded.error };
  }

  const { path, publicUrl } = uploaded;

  const { row, error } = await updateInstructorMediaColumn(supabase, authUid, instructorId, {
    profile_picture: publicUrl || null,
  });

  if (error) {
    await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, path);
    return { row: null, error };
  }

  await removeInstructorPublicImageQuietly(supabase, currentProfilePicture);

  return { row, error: null };
}

export async function uploadInstructorCvClient(
  authUid: string,
  instructorId: number,
  file: File,
  currentCvPath: string | null | undefined,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ row: InstructorProfileRow | null; error: string | null }> {
  if (!isValidInstructorCvFile(file)) {
    return { row: null, error: INSTRUCTOR_MEDIA_CV_ERROR };
  }
  if (file.size > CV_MAX_BYTES) {
    return { row: null, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  const storageFileName = buildTimestampedStorageFileName(
    file.name,
    file.name.includes(".") ? (file.name.split(".").pop() ?? "pdf") : "pdf",
  );
  const path = buildInstructorCvPath(instructorId, storageFileName);
  const oldPath = resolveInstructorCvStoragePath(String(currentCvPath ?? ""));

  const { error: uploadError } = await supabase.storage
    .from(INSTRUCTOR_CV_FILES_BUCKET)
    .upload(path, file, { upsert: false, contentType: file.type || undefined });

  if (uploadError) {
    console.error("[instructor-media] cv upload:", uploadError);
    return { row: null, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const { row, error } = await updateInstructorMediaColumn(supabase, authUid, instructorId, {
    cv_url: path,
  });

  if (error) {
    await removeStorageFileQuietly(supabase, INSTRUCTOR_CV_FILES_BUCKET, path);
    return { row: null, error };
  }

  if (oldPath && oldPath !== path) {
    await removeStorageFileQuietly(supabase, INSTRUCTOR_CV_FILES_BUCKET, oldPath);
  }

  return { row, error: null };
}

function diplomaFallbackExtension(file: File): string {
  const fromName = file.name.includes(".") ? (file.name.split(".").pop() ?? "") : "";
  const lower = fromName.toLowerCase();
  if (lower === "pdf" || lower === "jpg" || lower === "jpeg" || lower === "png") return lower;
  if (file.type === "application/pdf") return "pdf";
  if (file.type === "image/png") return "png";
  return "jpg";
}

export function resolveInstructorDiplomaStoragePath(pathOrUrl: string): string | null {
  const raw = String(pathOrUrl ?? "").trim();
  if (!raw) return null;
  if (!raw.includes("://")) {
    return raw.replace(/^\/+/, "");
  }

  try {
    const url = new URL(raw);
    const bucket = INSTRUCTOR_DIPLOMA_FILES_BUCKET;
    const markers = [
      `/storage/v1/object/sign/${bucket}/`,
      `/storage/v1/object/authenticated/${bucket}/`,
      `/storage/v1/object/public/${bucket}/`,
    ];
    for (const marker of markers) {
      const idx = url.pathname.indexOf(marker);
      if (idx >= 0) {
        return decodeURIComponent(url.pathname.slice(idx + marker.length));
      }
    }
  } catch {
    return null;
  }
  return null;
}

/** Private instructor-diploma-files bucket — yalnızca storage path döner, public URL yazılmaz. */
export async function uploadInstructorDiplomaFileToStorage(
  instructorId: number,
  file: File,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ path: string | null; error: string | null }> {
  if (!isValidInstructorDiplomaFile(file)) {
    return { path: null, error: INSTRUCTOR_MEDIA_DIPLOMA_ERROR };
  }
  if (file.size > INSTRUCTOR_DIPLOMA_MAX_BYTES) {
    return { path: null, error: INSTRUCTOR_MEDIA_DIPLOMA_SIZE_ERROR };
  }

  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  const storageFileName = buildTimestampedStorageFileName(file.name, diplomaFallbackExtension(file));
  const path = buildInstructorDiplomaPath(instructorId, storageFileName);

  const { error: uploadError } = await supabase.storage
    .from(INSTRUCTOR_DIPLOMA_FILES_BUCKET)
    .upload(path, file, { upsert: false, contentType: file.type || undefined });

  if (uploadError) {
    const uploadErr = uploadError as { code?: string; message?: string; details?: string; hint?: string };
    console.error(
      `[instructor-media] diploma upload | step=diploma_upload_result | code=${uploadErr.code ?? ""} | message=${uploadErr.message ?? ""} | details=${uploadErr.details ?? ""} | hint=${uploadErr.hint ?? ""}`,
    );
    return { path: null, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  return { path, error: null };
}

export async function removeInstructorDiplomaFileQuietly(
  path: string | null | undefined,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<void> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  await removeStorageFileQuietly(
    supabase,
    INSTRUCTOR_DIPLOMA_FILES_BUCKET,
    resolveInstructorDiplomaStoragePath(String(path ?? "")),
  );
}

export function instructorPrivateDocumentDisplayName(pathOrName: string): string {
  const raw = String(pathOrName ?? "").trim();
  if (!raw) return "";
  const segment = raw.split("/").pop() ?? raw;
  const withoutTimestamp = segment.match(/^\d+-(.+)$/);
  return withoutTimestamp ? withoutTimestamp[1] : segment;
}

function isStorageObjectNotFoundError(error: { message?: string } | null): boolean {
  const msg = String(error?.message ?? "").toLowerCase();
  return msg.includes("not found") || msg.includes("object not found");
}

export async function getInstructorCvViewUrlClient(
  cvUrlOrPath: string,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ url: string | null; isBlobUrl: boolean; error: string | null }> {
  const path = resolveInstructorCvStoragePath(cvUrlOrPath);
  if (!path) {
    return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_CV_NOT_FOUND_ERROR };
  }

  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  const { data, error } = await supabase.storage
    .from(INSTRUCTOR_CV_FILES_BUCKET)
    .createSignedUrl(path, 60 * 10);

  if (!error && data?.signedUrl) {
    return { url: data.signedUrl, isBlobUrl: false, error: null };
  }

  if (error) {
    console.error("[instructor-media] cv signed url:", error, { path, raw: cvUrlOrPath });
  }

  if (!isStorageObjectNotFoundError(error)) {
    return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const { data: fileData, error: downloadError } = await supabase.storage
    .from(INSTRUCTOR_CV_FILES_BUCKET)
    .download(path);

  if (!downloadError && fileData) {
    const objectUrl = URL.createObjectURL(fileData);
    return { url: objectUrl, isBlobUrl: true, error: null };
  }

  if (downloadError) {
    console.error("[instructor-media] cv download:", downloadError, { path, raw: cvUrlOrPath });
  }

  return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_CV_NOT_FOUND_ERROR };
}

export async function getInstructorDiplomaViewUrlClient(
  diplomaPath: string,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ url: string | null; isBlobUrl: boolean; error: string | null }> {
  const path = resolveInstructorDiplomaStoragePath(diplomaPath);
  if (!path) {
    return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  const { data, error } = await supabase.storage
    .from(INSTRUCTOR_DIPLOMA_FILES_BUCKET)
    .createSignedUrl(path, 60 * 10);

  if (!error && data?.signedUrl) {
    return { url: data.signedUrl, isBlobUrl: false, error: null };
  }

  if (error) {
    console.error("[instructor-media] diploma signed url:", error, { path, raw: diplomaPath });
  }

  if (!isStorageObjectNotFoundError(error)) {
    return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  const { data: fileData, error: downloadError } = await supabase.storage
    .from(INSTRUCTOR_DIPLOMA_FILES_BUCKET)
    .download(path);

  if (!downloadError && fileData) {
    const objectUrl = URL.createObjectURL(fileData);
    return { url: objectUrl, isBlobUrl: true, error: null };
  }

  if (downloadError) {
    console.error("[instructor-media] diploma download:", downloadError, { path, raw: diplomaPath });
  }

  return { url: null, isBlobUrl: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
}

/** Duyuru görseli — instructor_announcements.image_url / image_path için */
export async function uploadInstructorAnnouncementImageClient(
  instructorId: number,
  file: File,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ imageUrl: string; imagePath: string } | { error: string }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  const uploaded = await uploadInstructorPublicImage(
    supabase,
    instructorId,
    "announcements",
    file,
    ANNOUNCEMENT_IMAGE_MAX_BYTES,
  );
  if ("error" in uploaded) {
    return { error: uploaded.error };
  }
  return { imageUrl: uploaded.publicUrl, imagePath: uploaded.path };
}

export async function loadInstructorGalleryMediaClient(
  authUid: string,
  instructorId: number,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{
  items: InstructorGalleryMediaRow[];
  tableMissing: boolean;
  error: string | null;
}> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  const { data, error } = await supabase
    .from(INSTRUCTOR_MEDIA_TABLE)
    .select(
      "id, instructor_id, owner_auth_id, file_url, file_path, file_name, file_type, media_type, created_at",
    )
    .eq("instructor_id", instructorId)
    .eq("owner_auth_id", authUid)
    .eq("media_type", "gallery")
    .order("created_at", { ascending: false });

  if (error) {
    if (isInstructorMediaTableMissingError(error)) {
      return { items: [], tableMissing: true, error: null };
    }
    console.error("[instructor-media] gallery load:", error);
    return { items: [], tableMissing: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  return {
    items: (data as InstructorGalleryMediaRow[] | null) ?? [],
    tableMissing: false,
    error: null,
  };
}

export async function uploadInstructorGalleryImageClient(
  authUid: string,
  instructorId: number,
  file: File,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ item: InstructorGalleryMediaRow | null; tableMissing: boolean; error: string | null }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  const uploaded = await uploadInstructorPublicImage(
    supabase,
    instructorId,
    "gallery",
    file,
    GALLERY_IMAGE_MAX_BYTES,
  );
  if ("error" in uploaded) {
    return { item: null, tableMissing: false, error: uploaded.error };
  }

  const { path, publicUrl } = uploaded;

  const { data, error: insertError } = await supabase
    .from(INSTRUCTOR_MEDIA_TABLE)
    .insert({
      instructor_id: instructorId,
      owner_auth_id: authUid,
      file_url: publicUrl,
      file_path: path,
      file_name: file.name,
      file_type: file.type,
      media_type: "gallery",
    })
    .select(
      "id, instructor_id, owner_auth_id, file_url, file_path, file_name, file_type, media_type, created_at",
    )
    .single();

  if (insertError) {
    if (isInstructorMediaTableMissingError(insertError)) {
      await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, path);
      return { item: null, tableMissing: true, error: null };
    }
    console.error("[instructor-media] gallery insert:", insertError);
    await removeStorageFileQuietly(supabase, INSTRUCTOR_MEDIA_BUCKET, path);
    return { item: null, tableMissing: false, error: INSTRUCTOR_MEDIA_UPLOAD_ERROR };
  }

  return { item: data as InstructorGalleryMediaRow, tableMissing: false, error: null };
}

export async function deleteInstructorGalleryMediaClient(
  authUid: string,
  instructorId: number,
  item: InstructorGalleryMediaRow,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ error: string | null }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  await removeGalleryStorageForItem(supabase, item);

  const { error: deleteError } = await supabase
    .from(INSTRUCTOR_MEDIA_TABLE)
    .delete()
    .eq("id", item.id)
    .eq("instructor_id", instructorId)
    .eq("owner_auth_id", authUid)
    .eq("media_type", "gallery");

  if (deleteError) {
    console.error("[instructor-media] gallery row delete:", deleteError);
    return { error: INSTRUCTOR_MEDIA_DELETE_ERROR };
  }

  return { error: null };
}

export async function deleteInstructorProfilePhotoClient(
  authUid: string,
  instructorId: number,
  currentProfilePicture: string | null | undefined,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ row: InstructorProfileRow | null; error: string | null }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();

  await removeInstructorPublicImageQuietly(supabase, currentProfilePicture);

  const { row, error } = await updateInstructorMediaColumn(supabase, authUid, instructorId, {
    profile_picture: null,
  });

  if (error) {
    return { row: null, error };
  }

  return { row, error: null };
}

export async function deleteInstructorCvClient(
  authUid: string,
  instructorId: number,
  currentCvPath: string | null | undefined,
  supabaseArg?: ReturnType<typeof createSupabaseBrowserClient>,
): Promise<{ row: InstructorProfileRow | null; error: string | null }> {
  const supabase = supabaseArg ?? createSupabaseBrowserClient();
  const path = resolveInstructorCvStoragePath(String(currentCvPath ?? ""));

  await removeStorageFileQuietly(supabase, INSTRUCTOR_CV_FILES_BUCKET, path);

  const { row, error } = await updateInstructorMediaColumn(supabase, authUid, instructorId, {
    cv_url: null,
  });

  if (error) {
    return { row: null, error };
  }

  return { row, error: null };
}